<?php
/**
 * RiskReportApi
 * PHP version 7.4
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FuseClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FuseClient\ApiException;
use FuseClient\Configuration;
use FuseClient\HeaderSelector;
use FuseClient\ObjectSerializer;

/**
 * RiskReportApi Class Doc Comment
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RiskReportApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteConsumerRiskReport' => [
            'application/json',
        ],
        'getConsumerRiskReportCustomization' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteConsumerRiskReport
     *
     * Delete consumer risk report
     *
     * @param  string $consumer_risk_report_id consumer_risk_report_id (required)
     * @param  string $fuse_client_id fuse_client_id (required)
     * @param  string $fuse_api_key fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConsumerRiskReport'] to see the possible values for this operation
     *
     * @throws \FuseClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \FuseClient\Model\DeleteConsumerRiskReportResponse
     */
    public function deleteConsumerRiskReport($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['deleteConsumerRiskReport'][0])
    {
        list($response) = $this->deleteConsumerRiskReportWithHttpInfo($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, $contentType);
        return $response;
    }

    /**
     * Operation deleteConsumerRiskReportWithHttpInfo
     *
     * Delete consumer risk report
     *
     * @param  string $consumer_risk_report_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConsumerRiskReport'] to see the possible values for this operation
     *
     * @throws \FuseClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \FuseClient\Model\DeleteConsumerRiskReportResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteConsumerRiskReportWithHttpInfo($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['deleteConsumerRiskReport'][0])
    {
        $request = $this->deleteConsumerRiskReportRequest($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\FuseClient\Model\DeleteConsumerRiskReportResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\FuseClient\Model\DeleteConsumerRiskReportResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\FuseClient\Model\DeleteConsumerRiskReportResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\FuseClient\Model\DeleteConsumerRiskReportResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FuseClient\Model\DeleteConsumerRiskReportResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteConsumerRiskReportAsync
     *
     * Delete consumer risk report
     *
     * @param  string $consumer_risk_report_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConsumerRiskReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteConsumerRiskReportAsync($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['deleteConsumerRiskReport'][0])
    {
        return $this->deleteConsumerRiskReportAsyncWithHttpInfo($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteConsumerRiskReportAsyncWithHttpInfo
     *
     * Delete consumer risk report
     *
     * @param  string $consumer_risk_report_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConsumerRiskReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteConsumerRiskReportAsyncWithHttpInfo($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['deleteConsumerRiskReport'][0])
    {
        $returnType = '\FuseClient\Model\DeleteConsumerRiskReportResponse';
        $request = $this->deleteConsumerRiskReportRequest($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteConsumerRiskReport'
     *
     * @param  string $consumer_risk_report_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConsumerRiskReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteConsumerRiskReportRequest($consumer_risk_report_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['deleteConsumerRiskReport'][0])
    {

        // verify the required parameter 'consumer_risk_report_id' is set
        if ($consumer_risk_report_id === null || (is_array($consumer_risk_report_id) && count($consumer_risk_report_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consumer_risk_report_id when calling deleteConsumerRiskReport'
            );
        }

        // verify the required parameter 'fuse_client_id' is set
        if ($fuse_client_id === null || (is_array($fuse_client_id) && count($fuse_client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fuse_client_id when calling deleteConsumerRiskReport'
            );
        }

        // verify the required parameter 'fuse_api_key' is set
        if ($fuse_api_key === null || (is_array($fuse_api_key) && count($fuse_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fuse_api_key when calling deleteConsumerRiskReport'
            );
        }


        $resourcePath = '/v1/risk_report/consumer/{consumer_risk_report_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($fuse_client_id !== null) {
            $headerParams['Fuse-Client-Id'] = ObjectSerializer::toHeaderValue($fuse_client_id);
        }
        // header params
        if ($fuse_api_key !== null) {
            $headerParams['Fuse-Api-Key'] = ObjectSerializer::toHeaderValue($fuse_api_key);
        }

        // path params
        if ($consumer_risk_report_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consumer_risk_report_id' . '}',
                ObjectSerializer::toPathValue($consumer_risk_report_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Fuse-Api-Key');
        if ($apiKey !== null) {
            $headers['Fuse-Api-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Fuse-Client-Id');
        if ($apiKey !== null) {
            $headers['Fuse-Client-Id'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsumerRiskReportCustomization
     *
     * Get consumer risk report customization
     *
     * @param  string $consumer_risk_report_customization_id consumer_risk_report_customization_id (required)
     * @param  string $fuse_client_id fuse_client_id (required)
     * @param  string $fuse_api_key fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConsumerRiskReportCustomization'] to see the possible values for this operation
     *
     * @throws \FuseClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \FuseClient\Model\GetConsumerRiskReportCustomizationResponse
     */
    public function getConsumerRiskReportCustomization($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['getConsumerRiskReportCustomization'][0])
    {
        list($response) = $this->getConsumerRiskReportCustomizationWithHttpInfo($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, $contentType);
        return $response;
    }

    /**
     * Operation getConsumerRiskReportCustomizationWithHttpInfo
     *
     * Get consumer risk report customization
     *
     * @param  string $consumer_risk_report_customization_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConsumerRiskReportCustomization'] to see the possible values for this operation
     *
     * @throws \FuseClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \FuseClient\Model\GetConsumerRiskReportCustomizationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsumerRiskReportCustomizationWithHttpInfo($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['getConsumerRiskReportCustomization'][0])
    {
        $request = $this->getConsumerRiskReportCustomizationRequest($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\FuseClient\Model\GetConsumerRiskReportCustomizationResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\FuseClient\Model\GetConsumerRiskReportCustomizationResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\FuseClient\Model\GetConsumerRiskReportCustomizationResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\FuseClient\Model\GetConsumerRiskReportCustomizationResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FuseClient\Model\GetConsumerRiskReportCustomizationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsumerRiskReportCustomizationAsync
     *
     * Get consumer risk report customization
     *
     * @param  string $consumer_risk_report_customization_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConsumerRiskReportCustomization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsumerRiskReportCustomizationAsync($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['getConsumerRiskReportCustomization'][0])
    {
        return $this->getConsumerRiskReportCustomizationAsyncWithHttpInfo($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsumerRiskReportCustomizationAsyncWithHttpInfo
     *
     * Get consumer risk report customization
     *
     * @param  string $consumer_risk_report_customization_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConsumerRiskReportCustomization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsumerRiskReportCustomizationAsyncWithHttpInfo($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['getConsumerRiskReportCustomization'][0])
    {
        $returnType = '\FuseClient\Model\GetConsumerRiskReportCustomizationResponse';
        $request = $this->getConsumerRiskReportCustomizationRequest($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsumerRiskReportCustomization'
     *
     * @param  string $consumer_risk_report_customization_id (required)
     * @param  string $fuse_client_id (required)
     * @param  string $fuse_api_key (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConsumerRiskReportCustomization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConsumerRiskReportCustomizationRequest($consumer_risk_report_customization_id, $fuse_client_id, $fuse_api_key, string $contentType = self::contentTypes['getConsumerRiskReportCustomization'][0])
    {

        // verify the required parameter 'consumer_risk_report_customization_id' is set
        if ($consumer_risk_report_customization_id === null || (is_array($consumer_risk_report_customization_id) && count($consumer_risk_report_customization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consumer_risk_report_customization_id when calling getConsumerRiskReportCustomization'
            );
        }

        // verify the required parameter 'fuse_client_id' is set
        if ($fuse_client_id === null || (is_array($fuse_client_id) && count($fuse_client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fuse_client_id when calling getConsumerRiskReportCustomization'
            );
        }

        // verify the required parameter 'fuse_api_key' is set
        if ($fuse_api_key === null || (is_array($fuse_api_key) && count($fuse_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fuse_api_key when calling getConsumerRiskReportCustomization'
            );
        }


        $resourcePath = '/v1/risk_report/consumer/customization/{consumer_risk_report_customization_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($fuse_client_id !== null) {
            $headerParams['Fuse-Client-Id'] = ObjectSerializer::toHeaderValue($fuse_client_id);
        }
        // header params
        if ($fuse_api_key !== null) {
            $headerParams['Fuse-Api-Key'] = ObjectSerializer::toHeaderValue($fuse_api_key);
        }

        // path params
        if ($consumer_risk_report_customization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consumer_risk_report_customization_id' . '}',
                ObjectSerializer::toPathValue($consumer_risk_report_customization_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Fuse-Api-Key');
        if ($apiKey !== null) {
            $headers['Fuse-Api-Key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Fuse-Client-Id');
        if ($apiKey !== null) {
            $headers['Fuse-Client-Id'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
