<?php
/**
 * AccountSubtype
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountSubtype Class Doc Comment
 *
 * @category Class
 * @description The account&#39;s subtype
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountSubtype
{
    /**
     * Possible values of this enum
     */
    public const CHECKING = 'checking';

    public const SAVINGS = 'savings';

    public const CHECKING_OR_SAVINGS = 'checking_or_savings';

    public const BUSINESS_CHECKING_OR_SAVINGS = 'business_checking_or_savings';

    public const BUSINESS_SAVINGS = 'business_savings';

    public const MONEY_MARKET = 'money_market';

    public const CERTIFICATE_OF_DEPOSIT = 'certificate_of_deposit';

    public const TREASURY = 'treasury';

    public const CREDIT_CARD = 'credit_card';

    public const DEBIT_CARD = 'debit_card';

    public const BONDS = 'bonds';

    public const HSA = 'hsa';

    public const PAYPAL = 'paypal';

    public const PREPAID = 'prepaid';

    public const CASH_MANAGEMENT = 'cash_management';

    public const EBT = 'ebt';

    public const AUTO = 'auto';

    public const BUSINESS = 'business';

    public const COMMERCIAL = 'commercial';

    public const CONSTRUCTION = 'construction';

    public const CONSUMER = 'consumer';

    public const HOME_EQUITY = 'home_equity';

    public const FOREIGN = 'foreign';

    public const LOAN = 'loan';

    public const MORTGAGE = 'mortgage';

    public const OVERDRAFT = 'overdraft';

    public const LINE_OF_CREDIT = 'line_of_credit';

    public const STUDENT = 'student';

    public const _529 = '529';

    public const _401_A = '401_a';

    public const _401_K = '401_k';

    public const _403_B = '403_b';

    public const _457_B = '457_b';

    public const FUNDS = 'funds';

    public const BROKERAGE = 'brokerage';

    public const SECURITIES = 'securities';

    public const STOCKS = 'stocks';

    public const CASH_ISA = 'cash_isa';

    public const CRYPTO_EXCHANGE = 'crypto_exchange';

    public const EDUCATION_SAVING_ACCOUNT = 'education_saving_account';

    public const FIXED_ANNUITY = 'fixed_annuity';

    public const GIC = 'gic';

    public const HEALTH_REIMBURSEMENT_ARRANGEMENT = 'health_reimbursement_arrangement';

    public const IRA = 'ira';

    public const ISA = 'isa';

    public const KEOGH = 'keogh';

    public const LIF = 'lif';

    public const LIFE_INSURANCE = 'life_insurance';

    public const LIRA = 'lira';

    public const LRIF = 'lrif';

    public const LRSP = 'lrsp';

    public const MUTUAL_FUND = 'mutual_fund';

    public const NON_CUSTODIAL_WALLET = 'non_custodial_wallet';

    public const NON_TAXABLE_BROKERAGE_ACCOUNT = 'non_taxable_brokerage_account';

    public const OTHER_ANNUITY = 'other_annuity';

    public const OTHER_INSURANCE = 'other_insurance';

    public const PENSION = 'pension';

    public const PRIF = 'prif';

    public const PROFIT_SHARING_PLAN = 'profit_sharing_plan';

    public const QSHR = 'qshr';

    public const RDSP = 'rdsp';

    public const RESP = 'resp';

    public const RETIREMENT = 'retirement';

    public const RLIF = 'rlif';

    public const ROTH_IRA = 'roth_ira';

    public const ROTH_401_K = 'roth_401_k';

    public const RRIF = 'rrif';

    public const RRSP = 'rrsp';

    public const SARSEP = 'sarsep';

    public const SEP_IRA = 'sep_ira';

    public const SIMPLE_IRA = 'simple_ira';

    public const SIPP = 'sipp';

    public const STOCK_PLAN = 'stock_plan';

    public const TFSA = 'tfsa';

    public const TRUST = 'trust';

    public const UGMA = 'ugma';

    public const UTMA = 'utma';

    public const VARIABLE_ANNUITY = 'variable_annuity';

    public const SMALL_BUSINESS = 'small_business';

    public const PERSONAL = 'personal';

    public const PERSONAL_WITH_COLLATERAL = 'personal_with_collateral';

    public const _457 = '457';

    public const ROLLOVER_IRA = 'rollover_ira';

    public const TAXABLE = 'taxable';

    public const NON_TAXABLE = 'non_taxable';

    public const EMPLOYEE_STOCK_OWNERSHIP_PLAN = 'employee_stock_ownership_plan';

    public const INDIVIDUAL = 'individual';

    public const CASH_MANAGEMENT_ACCOUNT = 'cash_management_account';

    public const EMPLOYEE_STOCK_PURCHASE_PLAN = 'employee_stock_purchase_plan';

    public const REGISTERED_EDUCATION_SAVINGS_PLAN = 'registered_education_savings_plan';

    public const FIXED_ANNUITY_TRADITIONAL_IRA = 'fixed_annuity_traditional_ira';

    public const INHERITED_TRADITIONAL_IRA = 'inherited_traditional_ira';

    public const FIXED_ANNUITY_ROTH_IRA = 'fixed_annuity_roth_ira';

    public const VARIABLE_ANNUITY_ROTH_IRA = 'variable_annuity_roth_ira';

    public const INHERITED_ROTH_IRA = 'inherited_roth_ira';

    public const ADVISORY_ACCOUNT = 'advisory_account';

    public const BROKERAGE_MARGIN = 'brokerage_margin';

    public const CHARITABLE_GIFT_ACCOUNT = 'charitable_gift_account';

    public const CHURCH_ACCOUNT = 'church_account';

    public const CONSERVATORSHIP = 'conservatorship';

    public const CUSTODIAL = 'custodial';

    public const DEFINED_BENEFIT_PLAN = 'defined_benefit_plan';

    public const DEFINED_CONTRIBUTION_PLAN = 'defined_contribution_plan';

    public const EDUCATIONAL = 'educational';

    public const ESTATE = 'estate';

    public const EXECUTOR = 'executor';

    public const GROUP_RETIREMENT_SAVINGS_PLAN = 'group_retirement_savings_plan';

    public const GUARANTEED_INVESTMENT_CERTIFICATE = 'guaranteed_investment_certificate';

    public const INDEXED_ANNUITY = 'indexed_annuity';

    public const INVESTMENT_CLUB = 'investment_club';

    public const IRREVOCABLE_TRUST = 'irrevocable_trust';

    public const JOINT_TENANTS_BY_ENTIRETY = 'joint_tenants_by_entirety';

    public const JOINT_TENANTS_COMMUNITY_PROPERTY = 'joint_tenants_community_property';

    public const JOINT_TENANTS_IN_COMMON = 'joint_tenants_in_common';

    public const JOINT_TENANTS_WITH_RIGHTS_OF_SURVIVORSHIP = 'joint_tenants_with_rights_of_survivorship';

    public const KEOUGH_PLAN = 'keough_plan';

    public const LIVING_TRUST = 'living_trust';

    public const LOCKED_IN_RETIREMENT_ACCOUNT = 'locked_in_retirement_account';

    public const LOCKED_IN_RETIREMENT_INVESTMENT_FUND = 'locked_in_retirement_investment_fund';

    public const LOCKED_IN_RETIREMENT_SAVINGS_ACCOUNT = 'locked_in_retirement_savings_account';

    public const MONEY_PURCHASE_PLAN = 'money_purchase_plan';

    public const PARTNERSHIP = 'partnership';

    public const _409_A = '409_a';

    public const RPP = 'rpp';

    public const REVOCABLE_TRUST = 'revocable_trust';

    public const ROTH_CONVERSION = 'roth_conversion';

    public const SOLE_PROPRIETORSHIP = 'sole_proprietorship';

    public const SPOUSAL_IRA = 'spousal_ira';

    public const SPOUSAL_ROTH_IRA = 'spousal_roth_ira';

    public const TESTAMENTARY_TRUST = 'testamentary_trust';

    public const THRIFT_SAVINGS_PLAN = 'thrift_savings_plan';

    public const INHERITED_ANNUITY = 'inherited_annuity';

    public const CORPORATE_ACCOUNT = 'corporate_account';

    public const LIMITED_LIABILITY_ACCOUNT = 'limited_liability_account';

    public const BOAT = 'boat';

    public const POWERSPORTS = 'powersports';

    public const RV = 'rv';

    public const HELOC = 'heloc';

    public const VEHICLE_INSURANCE = 'vehicle_insurance';

    public const DISABILITY = 'disability';

    public const HEALTH = 'health';

    public const LONG_TERM_CARE = 'long_term_care';

    public const PROPERTY_AND_CASUALTY = 'property_and_casualty';

    public const UNIVERSAL_LIFE = 'universal_life';

    public const TERM_LIFE = 'term_life';

    public const WHOLE_LIFE = 'whole_life';

    public const ACCIDENTAL_DEATH_AND_DISMEMBERMENT = 'accidental_death_and_dismemberment';

    public const VARIABLE_UNIVERSAL_LIFE = 'variable_universal_life';

    public const REVOLVING = 'revolving';

    public const OTHER = 'other';

    public const TIME_DEPOSIT = 'time_deposit';

    public const ROTH = 'roth';

    public const MILITARY = 'military';

    public const INSTALLMENT = 'installment';

    public const INSTITUTIONAL_TRUST = 'institutional_trust';

    public const HOME_LINE_OF_CREDIT = 'home_line_of_credit';

    public const GUARDIAN = 'guardian';

    public const COMMERCIAL_LINE_OF_CREDIT = 'commercial_line_of_credit';

    public const CHARGE = 'charge';

    public const COVERDELL = 'coverdell';

    public const ESCROW = 'escrow';

    public const MINUS = '-';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHECKING,
            self::SAVINGS,
            self::CHECKING_OR_SAVINGS,
            self::BUSINESS_CHECKING_OR_SAVINGS,
            self::BUSINESS_SAVINGS,
            self::MONEY_MARKET,
            self::CERTIFICATE_OF_DEPOSIT,
            self::TREASURY,
            self::CREDIT_CARD,
            self::DEBIT_CARD,
            self::BONDS,
            self::HSA,
            self::PAYPAL,
            self::PREPAID,
            self::CASH_MANAGEMENT,
            self::EBT,
            self::AUTO,
            self::BUSINESS,
            self::COMMERCIAL,
            self::CONSTRUCTION,
            self::CONSUMER,
            self::HOME_EQUITY,
            self::FOREIGN,
            self::LOAN,
            self::MORTGAGE,
            self::OVERDRAFT,
            self::LINE_OF_CREDIT,
            self::STUDENT,
            self::_529,
            self::_401_A,
            self::_401_K,
            self::_403_B,
            self::_457_B,
            self::FUNDS,
            self::BROKERAGE,
            self::SECURITIES,
            self::STOCKS,
            self::CASH_ISA,
            self::CRYPTO_EXCHANGE,
            self::EDUCATION_SAVING_ACCOUNT,
            self::FIXED_ANNUITY,
            self::GIC,
            self::HEALTH_REIMBURSEMENT_ARRANGEMENT,
            self::IRA,
            self::ISA,
            self::KEOGH,
            self::LIF,
            self::LIFE_INSURANCE,
            self::LIRA,
            self::LRIF,
            self::LRSP,
            self::MUTUAL_FUND,
            self::NON_CUSTODIAL_WALLET,
            self::NON_TAXABLE_BROKERAGE_ACCOUNT,
            self::OTHER_ANNUITY,
            self::OTHER_INSURANCE,
            self::PENSION,
            self::PRIF,
            self::PROFIT_SHARING_PLAN,
            self::QSHR,
            self::RDSP,
            self::RESP,
            self::RETIREMENT,
            self::RLIF,
            self::ROTH_IRA,
            self::ROTH_401_K,
            self::RRIF,
            self::RRSP,
            self::SARSEP,
            self::SEP_IRA,
            self::SIMPLE_IRA,
            self::SIPP,
            self::STOCK_PLAN,
            self::TFSA,
            self::TRUST,
            self::UGMA,
            self::UTMA,
            self::VARIABLE_ANNUITY,
            self::SMALL_BUSINESS,
            self::PERSONAL,
            self::PERSONAL_WITH_COLLATERAL,
            self::_457,
            self::ROLLOVER_IRA,
            self::TAXABLE,
            self::NON_TAXABLE,
            self::EMPLOYEE_STOCK_OWNERSHIP_PLAN,
            self::INDIVIDUAL,
            self::CASH_MANAGEMENT_ACCOUNT,
            self::EMPLOYEE_STOCK_PURCHASE_PLAN,
            self::REGISTERED_EDUCATION_SAVINGS_PLAN,
            self::FIXED_ANNUITY_TRADITIONAL_IRA,
            self::INHERITED_TRADITIONAL_IRA,
            self::FIXED_ANNUITY_ROTH_IRA,
            self::VARIABLE_ANNUITY_ROTH_IRA,
            self::INHERITED_ROTH_IRA,
            self::ADVISORY_ACCOUNT,
            self::BROKERAGE_MARGIN,
            self::CHARITABLE_GIFT_ACCOUNT,
            self::CHURCH_ACCOUNT,
            self::CONSERVATORSHIP,
            self::CUSTODIAL,
            self::DEFINED_BENEFIT_PLAN,
            self::DEFINED_CONTRIBUTION_PLAN,
            self::EDUCATIONAL,
            self::ESTATE,
            self::EXECUTOR,
            self::GROUP_RETIREMENT_SAVINGS_PLAN,
            self::GUARANTEED_INVESTMENT_CERTIFICATE,
            self::INDEXED_ANNUITY,
            self::INVESTMENT_CLUB,
            self::IRREVOCABLE_TRUST,
            self::JOINT_TENANTS_BY_ENTIRETY,
            self::JOINT_TENANTS_COMMUNITY_PROPERTY,
            self::JOINT_TENANTS_IN_COMMON,
            self::JOINT_TENANTS_WITH_RIGHTS_OF_SURVIVORSHIP,
            self::KEOUGH_PLAN,
            self::LIVING_TRUST,
            self::LOCKED_IN_RETIREMENT_ACCOUNT,
            self::LOCKED_IN_RETIREMENT_INVESTMENT_FUND,
            self::LOCKED_IN_RETIREMENT_SAVINGS_ACCOUNT,
            self::MONEY_PURCHASE_PLAN,
            self::PARTNERSHIP,
            self::_409_A,
            self::RPP,
            self::REVOCABLE_TRUST,
            self::ROTH_CONVERSION,
            self::SOLE_PROPRIETORSHIP,
            self::SPOUSAL_IRA,
            self::SPOUSAL_ROTH_IRA,
            self::TESTAMENTARY_TRUST,
            self::THRIFT_SAVINGS_PLAN,
            self::INHERITED_ANNUITY,
            self::CORPORATE_ACCOUNT,
            self::LIMITED_LIABILITY_ACCOUNT,
            self::BOAT,
            self::POWERSPORTS,
            self::RV,
            self::HELOC,
            self::VEHICLE_INSURANCE,
            self::DISABILITY,
            self::HEALTH,
            self::LONG_TERM_CARE,
            self::PROPERTY_AND_CASUALTY,
            self::UNIVERSAL_LIFE,
            self::TERM_LIFE,
            self::WHOLE_LIFE,
            self::ACCIDENTAL_DEATH_AND_DISMEMBERMENT,
            self::VARIABLE_UNIVERSAL_LIFE,
            self::REVOLVING,
            self::OTHER,
            self::TIME_DEPOSIT,
            self::ROTH,
            self::MILITARY,
            self::INSTALLMENT,
            self::INSTITUTIONAL_TRUST,
            self::HOME_LINE_OF_CREDIT,
            self::GUARDIAN,
            self::COMMERCIAL_LINE_OF_CREDIT,
            self::CHARGE,
            self::COVERDELL,
            self::ESCROW,
            self::MINUS
        ];
    }
}


