<?php
/**
 * CountryCode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FuseClient\Model;
use \FuseClient\ObjectSerializer;

/**
 * CountryCode Class Doc Comment
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CountryCode
{
    /**
     * Possible values of this enum
     */
    public const AE = 'AE';

    public const AM = 'AM';

    public const AR = 'AR';

    public const AT = 'AT';

    public const AU = 'AU';

    public const BD = 'BD';

    public const BE = 'BE';

    public const BG = 'BG';

    public const BH = 'BH';

    public const BM = 'BM';

    public const BN = 'BN';

    public const BR = 'BR';

    public const BW = 'BW';

    public const BY = 'BY';

    public const CA = 'CA';

    public const CH = 'CH';

    public const CI = 'CI';

    public const CL = 'CL';

    public const CM = 'CM';

    public const CN = 'CN';

    public const CO = 'CO';

    public const CZ = 'CZ';

    public const DE = 'DE';

    public const _DO = 'DO';

    public const DZ = 'DZ';

    public const EC = 'EC';

    public const EG = 'EG';

    public const ES = 'ES';

    public const FI = 'FI';

    public const FK = 'FK';

    public const FR = 'FR';

    public const GB = 'GB';

    public const GG = 'GG';

    public const GH = 'GH';

    public const GM = 'GM';

    public const GR = 'GR';

    public const HK = 'HK';

    public const HU = 'HU';

    public const ID = 'ID';

    public const IE = 'IE';

    public const IL = 'IL';

    public const IM = 'IM';

    public const IN = 'IN';

    public const IT = 'IT';

    public const JE = 'JE';

    public const JO = 'JO';

    public const JP = 'JP';

    public const KE = 'KE';

    public const KH = 'KH';

    public const KR = 'KR';

    public const KW = 'KW';

    public const LA = 'LA';

    public const LB = 'LB';

    public const LK = 'LK';

    public const LT = 'LT';

    public const LU = 'LU';

    public const MC = 'MC';

    public const MD = 'MD';

    public const MK = 'MK';

    public const MO = 'MO';

    public const MT = 'MT';

    public const MU = 'MU';

    public const MV = 'MV';

    public const MX = 'MX';

    public const MY = 'MY';

    public const NG = 'NG';

    public const NL = 'NL';

    public const NP = 'NP';

    public const NZ = 'NZ';

    public const OM = 'OM';

    public const PE = 'PE';

    public const PH = 'PH';

    public const PK = 'PK';

    public const PL = 'PL';

    public const PT = 'PT';

    public const QA = 'QA';

    public const RO = 'RO';

    public const RU = 'RU';

    public const SA = 'SA';

    public const SE = 'SE';

    public const SG = 'SG';

    public const SK = 'SK';

    public const SL = 'SL';

    public const TH = 'TH';

    public const TR = 'TR';

    public const TW = 'TW';

    public const TZ = 'TZ';

    public const UA = 'UA';

    public const UG = 'UG';

    public const US = 'US';

    public const UY = 'UY';

    public const VN = 'VN';

    public const ZA = 'ZA';

    public const ZM = 'ZM';

    public const ZW = 'ZW';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AE,
            self::AM,
            self::AR,
            self::AT,
            self::AU,
            self::BD,
            self::BE,
            self::BG,
            self::BH,
            self::BM,
            self::BN,
            self::BR,
            self::BW,
            self::BY,
            self::CA,
            self::CH,
            self::CI,
            self::CL,
            self::CM,
            self::CN,
            self::CO,
            self::CZ,
            self::DE,
            self::_DO,
            self::DZ,
            self::EC,
            self::EG,
            self::ES,
            self::FI,
            self::FK,
            self::FR,
            self::GB,
            self::GG,
            self::GH,
            self::GM,
            self::GR,
            self::HK,
            self::HU,
            self::ID,
            self::IE,
            self::IL,
            self::IM,
            self::IN,
            self::IT,
            self::JE,
            self::JO,
            self::JP,
            self::KE,
            self::KH,
            self::KR,
            self::KW,
            self::LA,
            self::LB,
            self::LK,
            self::LT,
            self::LU,
            self::MC,
            self::MD,
            self::MK,
            self::MO,
            self::MT,
            self::MU,
            self::MV,
            self::MX,
            self::MY,
            self::NG,
            self::NL,
            self::NP,
            self::NZ,
            self::OM,
            self::PE,
            self::PH,
            self::PK,
            self::PL,
            self::PT,
            self::QA,
            self::RO,
            self::RU,
            self::SA,
            self::SE,
            self::SG,
            self::SK,
            self::SL,
            self::TH,
            self::TR,
            self::TW,
            self::TZ,
            self::UA,
            self::UG,
            self::US,
            self::UY,
            self::VN,
            self::ZA,
            self::ZM,
            self::ZW
        ];
    }
}


