<?php
/**
 * FinancialConnectionsInvestmentTransactionSubtype
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FuseClient\Model;
use \FuseClient\ObjectSerializer;

/**
 * FinancialConnectionsInvestmentTransactionSubtype Class Doc Comment
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FinancialConnectionsInvestmentTransactionSubtype
{
    /**
     * Possible values of this enum
     */
    public const ACCOUNT_FEE = 'account_fee';

    public const ADJUSTMENT = 'adjustment';

    public const ASSIGNMENT = 'assignment';

    public const BUY = 'buy';

    public const BUY_TO_COVER = 'buy_to_cover';

    public const CONTRIBUTION = 'contribution';

    public const DEPOSIT = 'deposit';

    public const DISTRIBUTION = 'distribution';

    public const DIVIDEND = 'dividend';

    public const DIVIDEND_REINVESTMENT = 'dividend_reinvestment';

    public const EXERCISE = 'exercise';

    public const EXPIRE = 'expire';

    public const FUND_FEE = 'fund_fee';

    public const INTEREST = 'interest';

    public const INTEREST_RECEIVABLE = 'interest_receivable';

    public const INTEREST_REINVESTMENT = 'interest_reinvestment';

    public const LEGAL_FEE = 'legal_fee';

    public const LOAN_PAYMENT = 'loan_payment';

    public const LONG_TERM_CAPITAL_GAIN = 'long_term_capital_gain';

    public const LONG_TERM_CAPITAL_GAIN_REINVESTMENT = 'long_term_capital_gain_reinvestment';

    public const MANAGEMENT_FEE = 'management_fee';

    public const MARGIN_EXPENSE = 'margin_expense';

    public const MERGER = 'merger';

    public const MISCELLANEOUS_FEE = 'miscellaneous_fee';

    public const NON_QUALIFIED_DIVIDEND = 'non_qualified_dividend';

    public const NON_RESIDENT_TAX = 'non_resident_tax';

    public const PENDING_CREDIT = 'pending_credit';

    public const PENDING_DEBIT = 'pending_debit';

    public const QUALIFIED_DIVIDEND = 'qualified_dividend';

    public const REBALANCE = 'rebalance';

    public const RETURN_OF_PRINCIPAL = 'return_of_principal';

    public const REQUEST = 'request';

    public const SELL = 'sell';

    public const SELL_SHORT = 'sell_short';

    public const SEND = 'send';

    public const SHORT_TERM_CAPITAL_GAIN = 'short_term_capital_gain';

    public const SHORT_TERM_CAPITAL_GAIN_REINVESTMENT = 'short_term_capital_gain_reinvestment';

    public const SPIN_OFF = 'spin_off';

    public const SPLIT = 'split';

    public const STOCK_DISTRIBUTION = 'stock_distribution';

    public const TAX = 'tax';

    public const TAX_WITHHELD = 'tax_withheld';

    public const TRADE = 'trade';

    public const TRANSFER = 'transfer';

    public const TRANSFER_FEE = 'transfer_fee';

    public const TRUST_FEE = 'trust_fee';

    public const UNQUALIFIED_GAIN = 'unqualified_gain';

    public const WITHDRAWAL = 'withdrawal';

    public const MINUS = '-';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACCOUNT_FEE,
            self::ADJUSTMENT,
            self::ASSIGNMENT,
            self::BUY,
            self::BUY_TO_COVER,
            self::CONTRIBUTION,
            self::DEPOSIT,
            self::DISTRIBUTION,
            self::DIVIDEND,
            self::DIVIDEND_REINVESTMENT,
            self::EXERCISE,
            self::EXPIRE,
            self::FUND_FEE,
            self::INTEREST,
            self::INTEREST_RECEIVABLE,
            self::INTEREST_REINVESTMENT,
            self::LEGAL_FEE,
            self::LOAN_PAYMENT,
            self::LONG_TERM_CAPITAL_GAIN,
            self::LONG_TERM_CAPITAL_GAIN_REINVESTMENT,
            self::MANAGEMENT_FEE,
            self::MARGIN_EXPENSE,
            self::MERGER,
            self::MISCELLANEOUS_FEE,
            self::NON_QUALIFIED_DIVIDEND,
            self::NON_RESIDENT_TAX,
            self::PENDING_CREDIT,
            self::PENDING_DEBIT,
            self::QUALIFIED_DIVIDEND,
            self::REBALANCE,
            self::RETURN_OF_PRINCIPAL,
            self::REQUEST,
            self::SELL,
            self::SELL_SHORT,
            self::SEND,
            self::SHORT_TERM_CAPITAL_GAIN,
            self::SHORT_TERM_CAPITAL_GAIN_REINVESTMENT,
            self::SPIN_OFF,
            self::SPLIT,
            self::STOCK_DISTRIBUTION,
            self::TAX,
            self::TAX_WITHHELD,
            self::TRADE,
            self::TRANSFER,
            self::TRANSFER_FEE,
            self::TRUST_FEE,
            self::UNQUALIFIED_GAIN,
            self::WITHDRAWAL,
            self::MINUS
        ];
    }
}


