<?php
/**
 * TransactionCategoryPrimary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TransactionCategoryPrimary Class Doc Comment
 *
 * @category Class
 * @description Primary transaction category
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionCategoryPrimary
{
    /**
     * Possible values of this enum
     */
    public const AUTO_AND_TRANSPORT = 'auto_and_transport';

    public const BILLS_AND_UTILITIES = 'bills_and_utilities';

    public const BUSINESS_SERVICES = 'business_services';

    public const EDUCATION = 'education';

    public const ENTERTAINMENT = 'entertainment';

    public const FEES_AND_CHARGES = 'fees_and_charges';

    public const FINANCIAL = 'financial';

    public const FOOD_AND_DINING = 'food_and_dining';

    public const GIFTS_AND_DONATIONS = 'gifts_and_donations';

    public const HEALTH_AND_FITNESS = 'health_and_fitness';

    public const HOME = 'home';

    public const INCOME = 'income';

    public const INVESTMENTS = 'investments';

    public const KIDS = 'kids';

    public const PERSONAL_CARE = 'personal_care';

    public const PETS = 'pets';

    public const SHOPPING = 'shopping';

    public const TAXES = 'taxes';

    public const TRANSFER = 'transfer';

    public const TRAVEL = 'travel';

    public const UNCATEGORIZED = 'uncategorized';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTO_AND_TRANSPORT,
            self::BILLS_AND_UTILITIES,
            self::BUSINESS_SERVICES,
            self::EDUCATION,
            self::ENTERTAINMENT,
            self::FEES_AND_CHARGES,
            self::FINANCIAL,
            self::FOOD_AND_DINING,
            self::GIFTS_AND_DONATIONS,
            self::HEALTH_AND_FITNESS,
            self::HOME,
            self::INCOME,
            self::INVESTMENTS,
            self::KIDS,
            self::PERSONAL_CARE,
            self::PETS,
            self::SHOPPING,
            self::TAXES,
            self::TRANSFER,
            self::TRAVEL,
            self::UNCATEGORIZED
        ];
    }
}


