<?php
/**
 * TransactionCategoryDetailed
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TransactionCategoryDetailed Class Doc Comment
 *
 * @category Class
 * @description Detailed transaction category
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionCategoryDetailed
{
    /**
     * Possible values of this enum
     */
    public const AUTO_AND_TRANSPORT = 'auto_and_transport';

    public const BILLS_AND_UTILITIES = 'bills_and_utilities';

    public const BUSINESS_SERVICES = 'business_services';

    public const EDUCATION = 'education';

    public const ENTERTAINMENT = 'entertainment';

    public const FEES_AND_CHARGES = 'fees_and_charges';

    public const FINANCIAL = 'financial';

    public const FOOD_AND_DINING = 'food_and_dining';

    public const GIFTS_AND_DONATIONS = 'gifts_and_donations';

    public const HEALTH_AND_FITNESS = 'health_and_fitness';

    public const HOME = 'home';

    public const INCOME = 'income';

    public const INVESTMENTS = 'investments';

    public const KIDS = 'kids';

    public const PERSONAL_CARE = 'personal_care';

    public const PETS = 'pets';

    public const SHOPPING = 'shopping';

    public const TAXES = 'taxes';

    public const TRANSFER = 'transfer';

    public const TRAVEL = 'travel';

    public const AUTO_INSURANCE = 'auto_insurance';

    public const AUTO_PAYMENT = 'auto_payment';

    public const GAS = 'gas';

    public const PARKING = 'parking';

    public const PUBLIC_TRANSPORTATION = 'public_transportation';

    public const SERVICE_AND_PARTS = 'service_and_parts';

    public const DOMAIN_NAMES = 'domain_names';

    public const FRAUD_PROTECTION = 'fraud_protection';

    public const HOME_PHONE = 'home_phone';

    public const HOSTING = 'hosting';

    public const INTERNET = 'internet';

    public const MOBILE_PHONE = 'mobile_phone';

    public const TELEVISION = 'television';

    public const UTILITIES = 'utilities';

    public const ADVERTISING = 'advertising';

    public const LEGAL = 'legal';

    public const OFFICE_SUPPLIES = 'office_supplies';

    public const PRINTING = 'printing';

    public const SHIPPING = 'shipping';

    public const BOOKS_AND_SUPPLIES = 'books_and_supplies';

    public const STUDENT_LOAN = 'student_loan';

    public const TUITION = 'tuition';

    public const AMUSEMENT = 'amusement';

    public const ARTS = 'arts';

    public const MOVIES_AND_DVDS = 'movies_and_dvds';

    public const MUSIC = 'music';

    public const NEWSPAPERS_AND_MAGAZINES = 'newspapers_and_magazines';

    public const ATM_FEE = 'atm_fee';

    public const BANKING_FEE = 'banking_fee';

    public const FINANCE_CHARGE = 'finance_charge';

    public const LATE_FEE = 'late_fee';

    public const SERVICE_FEE = 'service_fee';

    public const TRADE_COMMISSIONS = 'trade_commissions';

    public const FINANCIAL_ADVISOR = 'financial_advisor';

    public const LIFE_INSURANCE = 'life_insurance';

    public const ALCOHOL_AND_BARS = 'alcohol_and_bars';

    public const COFFEE_SHOPS = 'coffee_shops';

    public const FAST_FOOD = 'fast_food';

    public const GROCERIES = 'groceries';

    public const RESTAURANTS = 'restaurants';

    public const CHARITY = 'charity';

    public const GIFT = 'gift';

    public const DENTIST = 'dentist';

    public const DOCTOR = 'doctor';

    public const EYECARE = 'eyecare';

    public const GYM = 'gym';

    public const HEALTH_INSURANCE = 'health_insurance';

    public const PHARMACY = 'pharmacy';

    public const SPORTS = 'sports';

    public const FURNISHINGS = 'furnishings';

    public const HOME_IMPROVEMENT = 'home_improvement';

    public const HOME_INSURANCE = 'home_insurance';

    public const HOME_SERVICES = 'home_services';

    public const HOME_SUPPLIES = 'home_supplies';

    public const LAWN_AND_GARDEN = 'lawn_and_garden';

    public const MORTGAGE_AND_RENT = 'mortgage_and_rent';

    public const BONUS = 'bonus';

    public const INTEREST_INCOME = 'interest_income';

    public const PAYCHECK = 'paycheck';

    public const REIMBURSEMENT = 'reimbursement';

    public const RENTAL_INCOME = 'rental_income';

    public const RETURNED_PURCHASE = 'returned_purchase';

    public const BUY = 'buy';

    public const DEPOSIT = 'deposit';

    public const DIVIDEND_AND_CAP_GAINS = 'dividend_and_cap_gains';

    public const SELL = 'sell';

    public const WITHDRAWAL = 'withdrawal';

    public const ALLOWANCE = 'allowance';

    public const BABY_SUPPLIES = 'baby_supplies';

    public const BABYSITTER_AND_DAYCARE = 'babysitter_and_daycare';

    public const CHILD_SUPPORT = 'child_support';

    public const KIDS_ACTIVITIES = 'kids_activities';

    public const TOYS = 'toys';

    public const HAIR = 'hair';

    public const LAUNDRY = 'laundry';

    public const SPA_AND_MASSAGE = 'spa_and_massage';

    public const PET_FOOD_AND_SUPPLIES = 'pet_food_and_supplies';

    public const PET_GROOMING = 'pet_grooming';

    public const VETERINARY = 'veterinary';

    public const BOOKS = 'books';

    public const CLOTHING = 'clothing';

    public const HOBBIES = 'hobbies';

    public const SPORTING_GOODS = 'sporting_goods';

    public const FEDERAL_TAX = 'federal_tax';

    public const LOCAL_TAX = 'local_tax';

    public const PROPERTY_TAX = 'property_tax';

    public const SALES_TAX = 'sales_tax';

    public const STATE_TAX = 'state_tax';

    public const CREDIT_CARD_PAYMENT = 'credit_card_payment';

    public const TRANSFER_FOR_CASH_SPENDING = 'transfer_for_cash_spending';

    public const MORTGAGE_PAYMENT = 'mortgage_payment';

    public const AIR_TRAVEL = 'air_travel';

    public const HOTEL = 'hotel';

    public const RENTAL_CAR_AND_TAXI = 'rental_car_and_taxi';

    public const VACATION = 'vacation';

    public const CASH = 'cash';

    public const CHECK = 'check';

    public const UNCATEGORIZED = 'uncategorized';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTO_AND_TRANSPORT,
            self::BILLS_AND_UTILITIES,
            self::BUSINESS_SERVICES,
            self::EDUCATION,
            self::ENTERTAINMENT,
            self::FEES_AND_CHARGES,
            self::FINANCIAL,
            self::FOOD_AND_DINING,
            self::GIFTS_AND_DONATIONS,
            self::HEALTH_AND_FITNESS,
            self::HOME,
            self::INCOME,
            self::INVESTMENTS,
            self::KIDS,
            self::PERSONAL_CARE,
            self::PETS,
            self::SHOPPING,
            self::TAXES,
            self::TRANSFER,
            self::TRAVEL,
            self::AUTO_INSURANCE,
            self::AUTO_PAYMENT,
            self::GAS,
            self::PARKING,
            self::PUBLIC_TRANSPORTATION,
            self::SERVICE_AND_PARTS,
            self::DOMAIN_NAMES,
            self::FRAUD_PROTECTION,
            self::HOME_PHONE,
            self::HOSTING,
            self::INTERNET,
            self::MOBILE_PHONE,
            self::TELEVISION,
            self::UTILITIES,
            self::ADVERTISING,
            self::LEGAL,
            self::OFFICE_SUPPLIES,
            self::PRINTING,
            self::SHIPPING,
            self::BOOKS_AND_SUPPLIES,
            self::STUDENT_LOAN,
            self::TUITION,
            self::AMUSEMENT,
            self::ARTS,
            self::MOVIES_AND_DVDS,
            self::MUSIC,
            self::NEWSPAPERS_AND_MAGAZINES,
            self::ATM_FEE,
            self::BANKING_FEE,
            self::FINANCE_CHARGE,
            self::LATE_FEE,
            self::SERVICE_FEE,
            self::TRADE_COMMISSIONS,
            self::FINANCIAL_ADVISOR,
            self::LIFE_INSURANCE,
            self::ALCOHOL_AND_BARS,
            self::COFFEE_SHOPS,
            self::FAST_FOOD,
            self::GROCERIES,
            self::RESTAURANTS,
            self::CHARITY,
            self::GIFT,
            self::DENTIST,
            self::DOCTOR,
            self::EYECARE,
            self::GYM,
            self::HEALTH_INSURANCE,
            self::PHARMACY,
            self::SPORTS,
            self::FURNISHINGS,
            self::HOME_IMPROVEMENT,
            self::HOME_INSURANCE,
            self::HOME_SERVICES,
            self::HOME_SUPPLIES,
            self::LAWN_AND_GARDEN,
            self::MORTGAGE_AND_RENT,
            self::BONUS,
            self::INTEREST_INCOME,
            self::PAYCHECK,
            self::REIMBURSEMENT,
            self::RENTAL_INCOME,
            self::RETURNED_PURCHASE,
            self::BUY,
            self::DEPOSIT,
            self::DIVIDEND_AND_CAP_GAINS,
            self::SELL,
            self::WITHDRAWAL,
            self::ALLOWANCE,
            self::BABY_SUPPLIES,
            self::BABYSITTER_AND_DAYCARE,
            self::CHILD_SUPPORT,
            self::KIDS_ACTIVITIES,
            self::TOYS,
            self::HAIR,
            self::LAUNDRY,
            self::SPA_AND_MASSAGE,
            self::PET_FOOD_AND_SUPPLIES,
            self::PET_GROOMING,
            self::VETERINARY,
            self::BOOKS,
            self::CLOTHING,
            self::HOBBIES,
            self::SPORTING_GOODS,
            self::FEDERAL_TAX,
            self::LOCAL_TAX,
            self::PROPERTY_TAX,
            self::SALES_TAX,
            self::STATE_TAX,
            self::CREDIT_CARD_PAYMENT,
            self::TRANSFER_FOR_CASH_SPENDING,
            self::MORTGAGE_PAYMENT,
            self::AIR_TRAVEL,
            self::HOTEL,
            self::RENTAL_CAR_AND_TAXI,
            self::VACATION,
            self::CASH,
            self::CHECK,
            self::UNCATEGORIZED
        ];
    }
}


