<?php
/**
 * FinancialConnectionsAccountDetailsAccountNumberTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FuseClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FinancialConnectionsAccountDetailsAccountNumberTest Class Doc Comment
 *
 * @category    Class
 * @description FinancialConnectionsAccountDetailsAccountNumber
 * @package     FuseClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FinancialConnectionsAccountDetailsAccountNumberTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FinancialConnectionsAccountDetailsAccountNumber"
     */
    public function testFinancialConnectionsAccountDetailsAccountNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sort_code"
     */
    public function testPropertySortCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "swift_bic"
     */
    public function testPropertySwiftBic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bsb"
     */
    public function testPropertyBsb()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
