<?php
/**
 * RiskReportApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fuse
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace FuseClient\Test\Api;

use \FuseClient\Configuration;
use \FuseClient\ApiException;
use \FuseClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RiskReportApiTest Class Doc Comment
 *
 * @category Class
 * @package  FuseClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RiskReportApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteConsumerRiskReport
     *
     * Delete consumer risk report.
     *
     */
    public function testDeleteConsumerRiskReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getConsumerRiskReportCustomization
     *
     * Get consumer risk report customization.
     *
     */
    public function testGetConsumerRiskReportCustomization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
